"use strict";
// after-pack.cjs — wrap the Electron binary so the portable AppImage always
// launches with the Chromium SUID sandbox disabled.
//
// The bundled chrome-sandbox helper can never be root-owned 4755 inside an
// AppImage extracted to /tmp by a non-root user, so Electron's setuid sandbox
// host hard-crashes ("SUID sandbox helper binary was found, but is not
// configured correctly") before any app code runs. Setting ELECTRON_DISABLE_SANDBOX
// (and passing --no-sandbox) at the launch argv is the only reliable fix for a
// portable AppImage; app.commandLine.appendSwitch("no-sandbox") in main.js is
// applied too late to stop the setuid sandbox host check.
const fs = require("fs");
const path = require("path");

module.exports = async function afterPack(context) {
  if (context.electronPlatformName !== "linux") return;
  const exe = context.packager.appInfo.executableName || "pi-scope";
  const exePath = path.join(context.appOutDir, exe);
  const realName = exe + ".bin";
  const realPath = path.join(context.appOutDir, realName);
  // Already wrapped in a previous pass (idempotent guard).
  if (fs.existsSync(realPath)) return;
  if (!fs.existsSync(exePath) || fs.statSync(exePath).isDirectory()) return;

  fs.renameSync(exePath, realPath);
  const wrapper = [
    "#!/bin/sh",
    "# Generated by after-pack.cjs — disable the Chromium SUID sandbox for portable AppImage use.",
    'exec env ELECTRON_DISABLE_SANDBOX=1 "$(dirname "$0")/' + realName + '" --no-sandbox "$@"',
    "",
  ].join("\n");
  fs.writeFileSync(exePath, wrapper);
  fs.chmodSync(exePath, 0o755);
};
